import Head from "next/head";
import Image from "next/image";
import AboutMe from "../components/AboutMe";
import Consultation from "../components/Consultation";
import Hero from "../components/Hero";
import Nav from "../components/Navigation";
import Slider from "../components/Slider";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Single Page Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="py-10">
        <Nav />
        <Hero />
        <AboutMe />
        <Slider />
        <Consultation />
        <Nav />
      </div>
    </div>
  );
}
